[2025-03-19T16:36:14.013+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: faud_detection_pipeline.store_data_hdfs scheduled__2023-10-08T05:00:00+00:00 [queued]>
[2025-03-19T16:36:14.040+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: faud_detection_pipeline.store_data_hdfs scheduled__2023-10-08T05:00:00+00:00 [queued]>
[2025-03-19T16:36:14.041+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-19T16:36:14.080+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): store_data_hdfs> on 2023-10-08 05:00:00+00:00
[2025-03-19T16:36:14.092+0000] {standard_task_runner.py:57} INFO - Started process 23109 to run task
[2025-03-19T16:36:14.099+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'faud_detection_pipeline', 'store_data_hdfs', 'scheduled__2023-10-08T05:00:00+00:00', '--job-id', '1822', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmpa17rj72g']
[2025-03-19T16:36:14.105+0000] {standard_task_runner.py:85} INFO - Job 1822: Subtask store_data_hdfs
[2025-03-19T16:36:14.214+0000] {task_command.py:415} INFO - Running <TaskInstance: faud_detection_pipeline.store_data_hdfs scheduled__2023-10-08T05:00:00+00:00 [running]> on host 0009f5fb76aa
[2025-03-19T16:36:14.432+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='faud_detection_pipeline' AIRFLOW_CTX_TASK_ID='store_data_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2023-10-08T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-08T05:00:00+00:00'
[2025-03-19T16:36:14.436+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-19T16:36:14.438+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker cp /tmp/transactions.csv namenode:/tmp/transactions.csv && docker cp /tmp/customers.csv namenode:/tmp/customers.csv && docker cp /tmp/external_data.csv namenode:/tmp/external_data.csv && docker exec namenode bash -c "hdfs dfs -mkdir -p /data/transactions && hdfs dfs -mkdir -p /data/customers && hdfs dfs -mkdir -p /data/external_data && hdfs dfs -put -f /tmp/transactions.csv /data/transactions/transactions.csv && hdfs dfs -put -f /tmp/customers.csv /data/customers/customers.csv && hdfs dfs -put -f /tmp/external_data.csv /data/external_data/external_data.csv && rm -rf /tmp/transactions.csv /tmp/customers.csv /tmp/external_data.csv"']
[2025-03-19T16:36:14.470+0000] {subprocess.py:86} INFO - Output:
[2025-03-19T16:36:28.965+0000] {subprocess.py:93} INFO - 2025-03-19 16:36:28,962 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-19T16:36:33.981+0000] {subprocess.py:93} INFO - 2025-03-19 16:36:33,978 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-19T16:36:40.629+0000] {subprocess.py:93} INFO - 2025-03-19 16:36:40,625 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-19T16:36:41.542+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-19T16:36:41.621+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=faud_detection_pipeline, task_id=store_data_hdfs, execution_date=20231008T050000, start_date=20250319T163614, end_date=20250319T163641
[2025-03-19T16:36:41.671+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-19T16:36:41.731+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
