[2025-03-19T12:22:18.121+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_pipeline.store_data_hdfs scheduled__2023-10-09T15:00:00+00:00 [queued]>
[2025-03-19T12:22:18.135+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_pipeline.store_data_hdfs scheduled__2023-10-09T15:00:00+00:00 [queued]>
[2025-03-19T12:22:18.136+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-19T12:22:18.161+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): store_data_hdfs> on 2023-10-09 15:00:00+00:00
[2025-03-19T12:22:18.170+0000] {standard_task_runner.py:57} INFO - Started process 6228 to run task
[2025-03-19T12:22:18.175+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_pipeline', 'store_data_hdfs', 'scheduled__2023-10-09T15:00:00+00:00', '--job-id', '653', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmpfs7i1_uy']
[2025-03-19T12:22:18.178+0000] {standard_task_runner.py:85} INFO - Job 653: Subtask store_data_hdfs
[2025-03-19T12:22:18.247+0000] {task_command.py:415} INFO - Running <TaskInstance: fraud_detection_pipeline.store_data_hdfs scheduled__2023-10-09T15:00:00+00:00 [running]> on host 0009f5fb76aa
[2025-03-19T12:22:18.363+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fraud_detection_pipeline' AIRFLOW_CTX_TASK_ID='store_data_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-09T15:00:00+00:00'
[2025-03-19T12:22:18.364+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-19T12:22:18.366+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker cp /tmp/transactions.json namenode:/tmp/transactions.json && docker cp /tmp/customers.json namenode:/tmp/customers.json && docker cp /tmp/external_data.json namenode:/tmp/external_data.json && rm -rf /tmp/external_data.json  && rm -rf /tmp/customers.json  && rm -rf /tmp/transactions.json  && docker exec namenode bash -c "hdfs dfs -mkdir -p /data && hdfs dfs -put -f /tmp/transactions.json /data/transactions.json && hdfs dfs -put -f /tmp/customers.json /data/customers.json && hdfs dfs -put -f /tmp/external_data.json /data/external_data.json && rm -rf /tmp/customers.json  && rm -rf /tmp/customers.json  && rm -rf /tmp/external_data.json "']
[2025-03-19T12:22:18.379+0000] {subprocess.py:86} INFO - Output:
[2025-03-19T12:22:22.218+0000] {subprocess.py:93} INFO - 2025-03-19 12:22:22,215 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-19T12:22:24.974+0000] {subprocess.py:93} INFO - 2025-03-19 12:22:24,971 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-19T12:22:27.858+0000] {subprocess.py:93} INFO - 2025-03-19 12:22:27,855 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-19T12:22:28.513+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-19T12:22:28.549+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=fraud_detection_pipeline, task_id=store_data_hdfs, execution_date=20231009T150000, start_date=20250319T122218, end_date=20250319T122228
[2025-03-19T12:22:28.582+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-19T12:22:28.614+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
