[2025-03-21T13:03:48.784+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_fraud_detection_pipeline.store_data_hdfs manual__2025-03-21T13:03:45.667185+00:00 [queued]>
[2025-03-21T13:03:48.796+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_fraud_detection_pipeline.store_data_hdfs manual__2025-03-21T13:03:45.667185+00:00 [queued]>
[2025-03-21T13:03:48.797+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2025-03-21T13:03:48.815+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): store_data_hdfs> on 2025-03-21 13:03:45.667185+00:00
[2025-03-21T13:03:48.822+0000] {standard_task_runner.py:57} INFO - Started process 30607 to run task
[2025-03-21T13:03:48.826+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_fraud_detection_pipeline', 'store_data_hdfs', 'manual__2025-03-21T13:03:45.667185+00:00', '--job-id', '3570', '--raw', '--subdir', 'DAGS_FOLDER/dag_2.py', '--cfg-path', '/tmp/tmppx9sh8_j']
[2025-03-21T13:03:48.832+0000] {standard_task_runner.py:85} INFO - Job 3570: Subtask store_data_hdfs
[2025-03-21T13:03:48.887+0000] {task_command.py:415} INFO - Running <TaskInstance: test_fraud_detection_pipeline.store_data_hdfs manual__2025-03-21T13:03:45.667185+00:00 [running]> on host 445fc0f18383
[2025-03-21T13:03:48.982+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='abelchaguermohamed@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_fraud_detection_pipeline' AIRFLOW_CTX_TASK_ID='store_data_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:03:45.667185+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T13:03:45.667185+00:00'
[2025-03-21T13:03:48.985+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T13:03:48.987+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker cp /tmp/transactions.csv namenode:/tmp/transactions.csv && docker cp /tmp/customers.csv namenode:/tmp/customers.csv && docker cp /tmp/external_data.csv namenode:/tmp/external_data.csv && docker exec namenode bash -c "hdfs dfs -mkdir -p /data/transactions && hdfs dfs -mkdir -p /data/customers && hdfs dfs -mkdir -p /data/external_data && hdfs dfs -put -f /tmp/transactions.csv /data/transactions/transactions.csv && hdfs dfs -put -f /tmp/customers.csv /data/customers/customers.csv && hdfs dfs -put -f /tmp/external_data.csv /data/external_data/external_data.csv && rm -rf /tmp/transactions.csv /tmp/customers.csv /tmp/external_data.csv"']
[2025-03-21T13:03:48.997+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T13:03:55.821+0000] {subprocess.py:93} INFO - 2025-03-21 13:03:55,819 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-21T13:03:58.112+0000] {subprocess.py:93} INFO - 2025-03-21 13:03:58,109 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-21T13:04:00.342+0000] {subprocess.py:93} INFO - 2025-03-21 13:04:00,339 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-21T13:04:00.976+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-21T13:04:01.005+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=test_fraud_detection_pipeline, task_id=store_data_hdfs, execution_date=20250321T130345, start_date=20250321T130348, end_date=20250321T130401
[2025-03-21T13:04:01.006+0000] {taskinstance.py:1703} ERROR - Error when executing <lambda> callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1700, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/dag_2.py", line 29, in <lambda>
    to=context['params']['email'],
KeyError: 'email'
[2025-03-21T13:04:01.065+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-21T13:04:01.090+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
